### ISSUE TITLE
Better handle missing args in C# implementation

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-docker#184]
If I forget to pass `ImageName` as an argument to the `Image` component, I get this:

```
error: Running program '/Users/joeduffy/temp/docker-build/aws/csharp/bin/Debug/netcoreapp3.1/cbp-aws-csharp.dll' failed with an unhandled exception:
    System.NullReferenceException: Object reference not set to an instance of an object.
       at Pulumi.Input`1.op_Implicit(Input`1 input)
       at Pulumi.Docker.Image..ctor(String name, ImageArgs args, ComponentResourceOptions options)
       at Program.<>c.<<Main>b__0_0>d.MoveNext() in /Users/joeduffy/temp/docker-build/aws/csharp/Program.cs:line 37
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Stack.RunInitAsync(Func`1 init)
       at Pulumi.Output`1.GetValueAsync()
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

That looks to be because we immediately call this function without first validating arguments:

```
            this.ImageName = Output.Tuple(args.ImageName.ToOutput(), args.LocalImageName.ToOutputNullable(),
                                          args.SkipPush.ToOutput()).Apply(imageArgs =>
            {
```

Separately, are we not publishing PDBs for these DLLs? I was surprised not to get line numbers for the Pulumi parts in the stack trace.

**Comment by AaronFriel** [comment]
This should be fixed - or the error will match other native resources - with the v4 Image. As we're no longer relying on a component resource written in .NET.
