### ISSUE TITLE
3.2.0 is having issues publishing to AWS ECR

### ISSUE THREAD

**Issue by jamie1911** [pulumi/pulumi-docker#352]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

It appears 3.2.0 has an issue with AWS ECR. When building and running through the Dockerfile, it will get successfully build the image However, it fails with

```
docker:image:Image standardizerImage  Successfully built f1bbb3339f5d
    docker:image:Image standardizerImage  Successfully tagged xxxx.dkr.ecr.us-east-1.amazonaws.com/sdfsdfsdf/sdfsdfsdf/sdfsdfs-4446b65:git-commit-b5b8sdfsfsdff77
...
...
...


File "/builds/relaytx/relay-mldc/venv/lib/python3.9/site-packages/pulumi_docker/docker.py", line 444, in build_image
        raise ResourceError(
    pulumi_docker.docker.ResourceError: No digest available for image xxxx.dkr.ecr.us-east-1.amazonaws.com/sdfsdfsdf/sdfsdfs-4446b65:git-commit-b5b8sdfsfsdff77
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

Reverting to version 3.1.0 does, we do not experience this issue.

### Steps to reproduce

1. Use version 3.2.0
2. build docker image and publish to AWS CR
`  repo = aws.ecr.Repository(f"{group}/{prefix}")
    return docker.Image(
        f"{prefix}Image",
        build=docker.DockerBuild(
            context=context,
            dockerfile=dockerfile
        ),
        image_name=repo.repository_url.apply(
            lambda repo_name: f"{repo_name}:git-commit-{short_sha}"
        )
        if short_sha
        else repo.repository_url,
        registry=repo.registry_id.apply(get_registry_info),
    ) `

Expected: Docker image successfully publishes to AWS ECR
Actual: Error and no published docker image.

**Comment by guineveresaenger** [comment]
Thank you for filing this bug - we'll take a look as soon as we can.

**Comment by looprock** [comment]
I'm seeing this as well with GCP, it doesn't seem provider specific but looks like an older issue I found related to it not being able to retrieve the digest: 
``` docker:image:Image trackhearing-frontend  Successfully built 4ec5f33cbbbe
      docker:image:Image trackhearing-frontend  Successfully tagged gcr.io/trackhearing-dev/trackhearing-frontend:latest
      docker:image:Image trackhearing-frontend  sha256:4ec5f33cbbbe8afc9ca6c5b77c49127c16e72cc0f96ce9342e1f030484e95916
      docker:image:Image trackhearing-frontend  Image build succeeded.

      docker:image:Image trackhearing-backend  Successfully built 5e7a74c95ab2
      docker:image:Image trackhearing-backend  Successfully tagged gcr.io/trackhearing-dev/trackhearing-backend:latest
      pulumi:pulumi:Stack main-dev running error: Program failed with an unhandled exception:
      pulumi:pulumi:Stack main-dev running error: Traceback (most recent call last):
      pulumi:pulumi:Stack main-dev running error: an unhandled error occurred: Program exited with non-zero exit code: 1
      pulumi:pulumi:Stack main-dev  3 errors; 1 message

      pulumi_docker.docker.ResourceError: No digest available for image gcr.io/trackhearing-dev/trackhearing-backend
      error: an unhandled error occurred: Program exited with non-zero exit code: 1```

**Comment by looprock** [comment]
I'm seeing this with GCP as well, it doesn't seem to be provider specific. I saw a similar older issues referencing the same problem retrieving the digest. I can confirm rolling back to 3.1.0 fixes this:
```      docker:image:Image xxxx-frontend  Successfully built 4ec5f33cbbbe
      docker:image:Image xxxx-frontend  Successfully tagged gcr.io/xxxx-dev/xxxx-frontend:latest
      docker:image:Image xxxx-frontend  sha256:4ec5f33cbbbe8afc9ca6c5b77c49127c16e72cc0f96ce9342e1f030484e95916
      docker:image:Image xxxx-frontend  Image build succeeded.

      docker:image:Image xxxx-backend  Successfully built 5e7a74c95ab2
      docker:image:Image xxxx-backend  Successfully tagged gcr.io/xxxx-dev/xxxx-backend:latest
      pulumi:pulumi:Stack main-dev running error: Program failed with an unhandled exception:
      pulumi:pulumi:Stack main-dev running error: Traceback (most recent call last):
      pulumi:pulumi:Stack main-dev running error: an unhandled error occurred: Program exited with non-zero exit code: 1
      pulumi:pulumi:Stack main-dev  3 errors; 1 message

      pulumi_docker.docker.ResourceError: No digest available for image gcr.io/xxxx-dev/xxxx-backend
      error: an unhandled error occurred: Program exited with non-zero exit code: 1```

**Comment by guineveresaenger** [comment]
Hi @jamie1911 -

I'm struggling a bit duplicating this locally. Could you re-format your Python snippet so I can reproduce this bug in a similar context to yours?

It occurs to me that the main difference between 3.1.0 and 3.2.0 are [new SSH opts for RegistryAuth](https://www.pulumi.com/registry/packages/docker/api-docs/provider/#ssh_opts_python) - is it possible you're using SSH in your setup somewhere, and need to specify this field?

**Comment by jamie1911** [comment]
@guineveresaenger Hello! I was able to do some additional testing. When I do pulumi up locally from my workstation, it seems to be working with 3.2.0. My local AWS profile is configured correctly with my access keys. However, inside of the CI/CD system, we use DOCKER_AUTH_CONFIG environment variable because the EC2 instance has an Instance Profile attached with the correct access. This environment variable sets the authentication for docker which allows it to use the ECR helper to get the credentials. Maybe something with this is incompatible all of sudden? 

the DOCKER_AUTH_CONFIG environment has the following:
```
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "xcvxcvxcvxcvxcvxc="
		}
	},
	"credHelpers": {
		"4445556666777.dkr.ecr.us-east-1.amazonaws.com": "ecr-login"
	}
}
```

the `__main__.py` has the following:
```

"""An AWS Python Pulumi program"""
import base64
import pulumi
import pulumi_aws as aws
import pulumi_docker as docker


def register_auto_tags(auto_tags):
    pulumi.runtime.register_stack_transformation(lambda args: auto_tag(args, auto_tags))


def auto_tag(args, auto_tags):
    """ Applies the given tags to the resource properties if applicable. Autoscaling Group needs GroupTagArgs, exclude it"""
    if (hasattr(args.resource, "tags") and not args.type_ == 'aws:autoscaling/group:Group'):
        args.props["tags"] = {**(args.props["tags"] or {}), **auto_tags}
        return pulumi.ResourceTransformationResult(args.props, args.opts)


def register_standard_tags():
    register_auto_tags(
        {
            "PulumiProject": pulumi.get_project(),
            "Stack": pulumi.get_stack(),
            "Deployment": "Pulumi",
        }
    )

def get_registry_info(rid) -> docker.ImageRegistry:
    creds = aws.ecr.get_credentials(registry_id=rid)
    decoded = base64.b64decode(creds.authorization_token).decode()
    parts = decoded.split(":")
    if len(parts) != 2:
        raise Exception("Invalid credentials")
    return docker.ImageRegistry(creds.proxy_endpoint, parts[0], parts[1])

register_standard_tags()

repo = aws.ecr.Repository('test/test-docker')
registry_info = repo.registry_id.apply(get_registry_info)
image = docker.Image('test-ubuntu', build=docker.DockerBuild(context='.', dockerfile="./Dockerfile"),
                     image_name=repo.repository_url,
                     registry=registry_info)

```

**Comment by feliperoveran** [comment]
I'm having the same issue as @jamie1911 where it works locally with `3.2.0` but fails in CI.
In our case, we are pushing the image to GCP and running the pipelines on GH Actions.

I was able to reproduce it locally but only once. still couldn't figure out why, though. 
the only thing I was able to notice is that it seems to break (more often?) for larger images

**Comment by jamie1911** [comment]
Upon further testing. I installed the ECR Credential Helper on the CI/CD system and for testing purposes, set the ~/.docker/config.json to:
```
{
	"credsStore": "ecr-login"
}
```

I then updated my code above to:
```
repo = aws.ecr.Repository('test/test-docker')
registry_info = None
image = docker.Image('test-ubuntu', build=docker.DockerBuild(context='.', dockerfile="./Dockerfile"),
                     image_name=repo.repository_url,
                     registry=registry_info)
```

I can now push to the ECR repo.

For whatever reason, the 3.2.0 version doesn't like the temporary credentials grabbed from `aws.ecr.get_credentials()`

We have been using the temporary method gathered here: https://www.pulumi.com/blog/build-publish-containers-iac/#authenticate-with-temporary-ecr-access-token but that no longer appears to work correctly.

I set the CI system to use this for AWS: https://www.pulumi.com/blog/build-publish-containers-iac/#authenticate-with-temporary-ecr-access-token and it is working again. I will have to change a lot of stuff to get 3.2.0 working in our env.

**Comment by guineveresaenger** [comment]
Thank you for the deep dive and workaround @jamie1911.

We're hoping to have time to give this provider some focused love soon.

**Comment by jamie1911** [comment]
@guineveresaenger I take it back, it still happens with `registry_info = None` 

The strange part is, it happened again. I then re-kicked off the job and since the job fell on the same server, docker used the previous build cache, and then it was able to successfully complete.

First run:
```
  docker:image:Image test-ubuntu  Step 4/4 : ENTRYPOINT ["/bin/bash"]
    docker:image:Image test-ubuntu   ---> Running in 1e1cf98f1c46
    docker:image:Image test-ubuntu  Removing intermediate container 1e1cf98f1c46
    docker:image:Image test-ubuntu   ---> 98655f9aaf13
    docker:image:Image test-ubuntu  Successfully built 98655f9aaf13
    docker:image:Image test-ubuntu  Successfully tagged 2343242342342.dkr.ecr.us-east-1.amazonaws.com/test/test-docker-5365e46:latest
    pulumi:pulumi:Stack docker-test-dev running error: Program failed with an unhandled exception:
    pulumi:pulumi:Stack docker-test-dev running error: Traceback (most recent call last):
    pulumi:pulumi:Stack docker-test-dev running error: an unhandled error occurred: Program exited with non-zero exit code: 1
    pulumi:pulumi:Stack docker-test-dev  3 errors
 
Diagnostics:
  pulumi:pulumi:Stack (docker-test-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/root/.pulumi/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/stack.py", line 110, in wait_for_rpcs
        raise exception
      File "/usr/local/lib/python3.9/dist-packages/pulumi/output.py", line 98, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/local/lib/python3.9/dist-packages/pulumi/output.py", line 214, in run
        return await cast(Awaitable[U], transformed)
      File "/usr/local/lib/python3.9/dist-packages/pulumi_docker/docker.py", line 243, in build_and_push_image
        build_result = await build_image(base_image_name, path_or_build, log_resource, cache_from)
      File "/usr/local/lib/python3.9/dist-packages/pulumi_docker/docker.py", line 444, in build_image
        raise ResourceError(
    pulumi_docker.docker.ResourceError: No digest available for image 2343242342342.dkr.ecr.us-east-1.amazonaws.com/test/test-docker-5365e46
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

Second retry
```
docker:image:Image test-ubuntu   ---> Using cache
    docker:image:Image test-ubuntu   ---> 485068ef9c36
    docker:image:Image test-ubuntu  Step 4/4 : ENTRYPOINT ["/bin/bash"]
    docker:image:Image test-ubuntu   ---> Using cache
    docker:image:Image test-ubuntu   ---> 98655f9aaf13
    docker:image:Image test-ubuntu  Successfully built 98655f9aaf13
    docker:image:Image test-ubuntu  Successfully tagged 2343242342342.dkr.ecr.us-east-1.amazonaws.com/test/test-docker-5365e46:latest
    docker:image:Image test-ubuntu  sha256:98655f9aaf13469989bad42a8443e63ba699933010eaa672eaaff6f6e6e92d29
    docker:image:Image test-ubuntu  Image build succeeded.
    pulumi:pulumi:Stack docker-test-dev  
```

**Comment by qdzlug** [comment]
Seeing this in our environment as well; we see the following:

```
Previewing update (jaynew01)

View Live: https://app.pulumi.com/qdzlug/kic-image-push/jaynew01/previews/1672830f-f91d-49ac-81cd-18a90724ef90

     Type                               Name                                Plan       
 +   pulumi:pulumi:Stack                kic-image-push-jaynew01             create     
 +   └─ pulumi-python:dynamic:Resource  ingress-controller-repository-push  create     
 
Resources:
    + 2 to create

Updating (jaynew01)

View Live: https://app.pulumi.com/qdzlug/kic-image-push/jaynew01/updates/1

     Type                               Name                                Status      Info
 +   pulumi:pulumi:Stack                kic-image-push-jaynew01             created     7 messages
 +   └─ pulumi-python:dynamic:Resource  ingress-controller-repository-push  created     
 
Diagnostics:
  pulumi:pulumi:Stack (kic-image-push-jaynew01):
    /home/jschmidt/data/repos/kic-reference-architectures/pulumi/python/utility/kic-image-push/repository_push.py:83: RuntimeWarning: coroutine 'login_to_registry' was never awaited
      docker.login_to_registry(registry=registry, log_resource=self.resource)
    RuntimeWarning: Enable tracemalloc to get the object allocation traceback
    /home/jschmidt/data/repos/kic-reference-architectures/pulumi/python/utility/kic-image-push/repository_push.py:90: RuntimeWarning: coroutine 'tag_and_push_image' was never awaited
      docker.tag_and_push_image(repository_url=repository_url,
    RuntimeWarning: Enable tracemalloc to get the object allocation traceback
    info: Tagged and pushed image [nginx/nginx-ingress:2.2.0] to [369313531325.dkr.ecr.us-west-2.amazonaws.com/ingress-controller-jaynew01:2.2.0]
 
Outputs:
    ecr_repository: {
        ecr_image_id        : "sha256:5f3cd9092a9002e5d73af22ba1737ceb0ee491e457ad55e49ed6b0ddec8849a4"
        ecr_image_name      : "369313531325.dkr.ecr.us-west-2.amazonaws.com/ingress-controller-jaynew01:2.2.0"
        id                  : "7834ac50-3178-49e2-a918-dd6525b770d2"
        image_id            : "sha256:5f3cd9092a9002e5d73af22ba1737ceb0ee491e457ad55e49ed6b0ddec8849a4"
        image_name          : "nginx/nginx-ingress:2.2.0"
        image_tag           : "2.2.0"
        repository_password : [secret]
        repository_url      : "369313531325.dkr.ecr.us-west-2.amazonaws.com/ingress-controller-jaynew01"
        repository_username : [secret]
        urn                 : "urn:pulumi:jaynew01::kic-image-push::pulumi-python:dynamic:Resource::ingress-controller-repository-push"
    }

Resources:
    + 2 created

Duration: 4s
```

https://github.com/nginxinc/kic-reference-architectures/issues/134

**Comment by ShedPlant** [comment]
I saw:

```
      File "/Users/shed/Documents/GitHub/expend-backend/projects/x-ray-daemon/.venv/lib/python3.9/site-packages/pulumi_docker/docker.py", line 437, in build_image
        await docker_build(image_name, build, log_resource, cache_from)
      File "/Users/shed/Documents/GitHub/expend-backend/projects/x-ray-daemon/.venv/lib/python3.9/site-packages/pulumi_docker/docker.py", line 479, in docker_build
        for image in cache_from:
    TypeError: 'coroutine' object is not iterable
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

When passing in `cache_from=True` in `DockerBuild` object to `Image` object.

Downgraded to 3.1.0 and happy again.

**Comment by jkodroff** [comment]
@ShedPlant Your issue is covered in https://github.com/pulumi/pulumi-docker/issues/366

**Comment by Lampboii** [comment]
This is still happening and pulumi-docker==3.1.0 causes pulumi to just hang. I am trying to build a local image and not push it

**Comment by guineveresaenger** [comment]
@Lampboii what version are you using?

**Comment by Lampboii** [comment]
Never mind, pulumi_docker==3.1.0 fixed actually fixed my issue it just outputs nothing until the image is built so it looked like it was hanging

**Comment by jamie1911** [comment]
Wait, why is it closed? pinning to an old version, doesn't seem like a valid fix.
