### ISSUE TITLE
Error when using pull_cache method

### ISSUE THREAD

**Issue by killouts** [pulumi/pulumi-docker#366]
### What happened?

This issue occurs when I set the `cache_from` field in `DockerBuild` to `True`.

```bash
Diagnostics:
  pulumi:pulumi:Stack (aidp-streams-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/Users/lapetus/.pyenv/versions/3.9.11/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
        return future.result()
      File "/Users/lapetus/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/lapetus/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/lapetus/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 110, in wait_for_rpcs
        raise exception
      File "/Users/lapetus/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 685, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "/Users/lapetus/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 174, in serialize_properties
        result = await serialize_property(
      File "/Users/lapetus/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 342, in serialize_property
        is_known = await output._is_known
      File "/Users/lapetus/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 514, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/Users/lapetus/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 124, in prepare_resource
        serialized_props = await rpc.serialize_properties(
      File "/Users/lapetus/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 174, in serialize_properties
        result = await serialize_property(
      File "/Users/lapetus/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 342, in serialize_property
        is_known = await output._is_known
      File "/Users/lapetus/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pulumi/output.py", line 98, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/Users/lapetus/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pulumi/output.py", line 214, in run
        return await cast(Awaitable[U], transformed)
      File "/Users/lapetus/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pulumi_docker/docker.py", line 243, in build_and_push_image
        build_result = await build_image(base_image_name, path_or_build, log_resource, cache_from)
      File "/Users/lapetus/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pulumi_docker/docker.py", line 437, in build_image
        await docker_build(image_name, build, log_resource, cache_from)
      File "/Users/lapetus/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pulumi_docker/docker.py", line 479, in docker_build
        for image in cache_from:
    TypeError: 'coroutine' object is not iterable
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

### Steps to reproduce

```python
docker_image = pulumi_docker.Image(
    IMAGE_RESOURCE_NAME,
    image_name=ecr_repository.repository_url,
    build=pulumi_docker.DockerBuild(
        args={"BUILDKIT_INLINE_CACHE": 1},
        cache_from=True, # A problem occurred here.
        context=SOURCE_FILE_PATH,
        extra_options=["--platform=linux/amd64"],
    ),
)
```

### Expected Behavior

The above error should not occur

### Actual Behavior

The above error occurred when running `pulumi up`

### Versions used

Use the latest version

### Additional context

Apply `async` to `pull_cache` method on **Dec 21, 2021**
* https://github.com/pulumi/pulumi-docker/commit/17f180b00d36d499165311fadb3e1fcad207e625#diff-a7db60322612a03c482e85afaba0bbdb6f491cc7cb434cb4cfe270a5b23e8b82R361

I guess it was caused by missing `await` keyword when calling `pull_cache` in the file below
* https://github.com/pulumi/pulumi-docker/blob/master/sdk/python/pulumi_docker/docker.py#L239

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkodroff** [comment]
@killouts I've submitted a PR which should hopefully fix the issue. When it's merged we'll create a bug fix release.

**Comment by jkodroff** [comment]
@killouts Sorry for the delay - I need to add an acceptance test for this and was traveling to an event. Hoping to complete this today.

**Comment by jkodroff** [comment]
@killouts So I eyeballed the change, and the fix made perfect sense - missing `await`. However, my PR review sensibly requested that I create a failing test case, and I am having trouble doing so. Could you provide a minimal but complete example that replicates the issue for you?

**Comment by AaronFriel** [comment]
This issue should be resolved with the new implementation of the [Docker Image resource in v4](https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.0)! See our blog post for more info: https://www.pulumi.com/blog/build-images-50x-faster-docker-v4/

The new resource no longer relies on per-language implementations, which should solve the crash in the provider awaiting a coroutine.

As well with the new resource, the code provided may need to change to use `cacheFrom` specifying a source image name (`registry.example.com/foo/bar:latest`). See the blog post and release notes linked in this comment for details.
