### ISSUE TITLE
Tests that push to ECR fail: No digest available for image 

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-docker#409]
The tests `TestAwsPy` and `TestDockerfilePy` fail non-deterministically with the following error message:

```
  Diagnostics:
    pulumi:pulumi:Stack (aws-py-p-it-fv-az201-8-aws-py-1828628b):
      /home/runner/work/pulumi-docker/pulumi-docker/sdk/python/bin/pulumi_docker/docker.py:232: RuntimeWarning: coroutine 'use_docker_password_stdin' was never awaited
        await login_to_registry(registry, log_resource)
      RuntimeWarning: Enable tracemalloc to get the object allocation traceback
   
      error: Program failed with an unhandled exception:
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/pulumi/3.44.2/x64/pulumi-language-python-exec", line 192, in <module>
          loop.run_until_complete(coro)
        File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
          return future.result()
        File "/tmp/p-it-fv-az201-8-aws-py-1828628b-3300966659/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
          await run_pulumi_func(lambda: Stack(func))
        File "/tmp/p-it-fv-az201-8-aws-py-1828628b-3300966659/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
          await wait_for_rpcs()
        File "/tmp/p-it-fv-az201-8-aws-py-1828628b-3300966659/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 110, in wait_for_rpcs
          raise exception
        File "/tmp/p-it-fv-az201-8-aws-py-1828628b-3300966659/venv/lib/python3.9/site-packages/pulumi/output.py", line 100, in is_value_known
          return await is_known and not contains_unknowns(await future)
        File "/tmp/p-it-fv-az201-8-aws-py-1828628b-3300966659/venv/lib/python3.9/site-packages/pulumi/output.py", line 216, in run
          return await cast(Awaitable[U], transformed)
        File "/home/runner/work/pulumi-docker/pulumi-docker/sdk/python/bin/pulumi_docker/docker.py", line 243, in build_and_push_image
          build_result = await build_image(base_image_name, path_or_build, log_resource, cache_from)
        File "/home/runner/work/pulumi-docker/pulumi-docker/sdk/python/bin/pulumi_docker/docker.py", line 444, in build_image
          raise ResourceError(
      pulumi_docker.docker.ResourceError: No digest available for image ***.dkr.ecr.us-west-2.amazonaws.com/my-repo-1-9f072d4
```

I think there's a chance the issue could be around here, since we're doing some ususual code with `async`: https://github.com/pulumi/pulumi-docker/blob/master/sdk/python/pulumi_docker/docker.py#L533-L541

It's also worth noting that the code linked above was introduced in v3.2.0, which is when folks started having issues like #352.

**Comment by AaronFriel** [comment]
This issue should be resolved with the new implementation of the [Docker Image resource in v4](https://github.com/pulumi/pulumi-docker/releases/tag/v4.0.0)!
