### ISSUE TITLE
Image Build Args containing an resource output panics: "interface conversion: interface {} is resource.Computed, not resource.PropertyMap"

### ISSUE THREAD

**Issue by jlewicki-nevo** [pulumi/pulumi-docker#565]
### What happened?

A panic occurs when building a docker image,  where the `Build.Args` InputMap contains an entry with an output from another resource.

```
Diagnostics:
  pulumi:pulumi:Stack (docker-test-dev):
    panic: interface conversion: interface {} is resource.Computed, not resource.PropertyMap
    goroutine 97 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/resource.PropertyValue.ObjectValue(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.56.0/go/common/resource/properties.go:431
    github.com/pulumi/pulumi-docker/provider/v4.marshalArgs({{0x13eef40?, 0xc000389890?}})
        /home/runner/work/pulumi-docker/pulumi-docker/provider/image.go:440 +0x217
    github.com/pulumi/pulumi-docker/provider/v4.marshalBuildAndApplyDefaults({{0x14fd6c0?, 0xc000470930?}})
        /home/runner/work/pulumi-docker/pulumi-docker/provider/image.go:382 +0x245
    github.com/pulumi/pulumi-docker/provider/v4.(*dockerNativeProvider).Check(0xc0007aec80, {0x17e35c8, 0xc0004708d0}, 0xc000115bc0)
        /home/runner/work/pulumi-docker/pulumi-docker/provider/provider.go:117 +0x205
    github.com/pulumi/pulumi-docker/provider/v4.dockerHybridProvider.Check({{}, {0x21a1260, 0x25dfe, 0x25dfe}, {0x17cebd4, 0x6}, {0x17efb10, 0xc0005aa280}, {0x17efa60, 0xc0007aec80}}, ...)
        /home/runner/work/pulumi-docker/pulumi-docker/provider/hybrid.go:96 +0xd7
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler.func1({0x17e35c8, 0xc0004708d0}, {0x14bc260?, 0xc000115bc0})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.56.0/proto/go/provider_grpc.pb.go:537 +0x78
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x17e35c8, 0xc000470690}, {0x14bc260, 0xc000115bc0}, 0xc0003179a0, 0xc0004902d0)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler({0x1532920?, 0xc0000b0fa0}, {0x17e35c8, 0xc000470690}, 0xc0006433b0, 0xc000477e40)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.56.0/proto/go/provider_grpc.pb.go:539 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000308000, {0x17eb7c0, 0xc0005d2ea0}, 0xc00012ec60, 0xc0005786c0, 0x21e2ab0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1336 +0xd33
    google.golang.org/grpc.(*Server).handleStream(0xc000308000, {0x17eb7c0, 0xc0005d2ea0}, 0xc00012ec60, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1704 +0xa36
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

  docker:index:Image (test):
    error: error reading from server: EOF
```

### Expected Behavior

The image to be created. This scenario worked as expected when using `Pulumi.Docker` 3.6.1.

### Steps to reproduce

```
public class DockerStack : Stack {

   public DockerStack() {
      // I just use a plugin here arbitrarily.  I think consuming output from any resource might cause the error
      var plugin = new Plugin("sample-plugin", new() {
         Envs = new[] {  "DEBUG=1"  },
      });

      var _ = new Image("test", new ImageArgs {
         SkipPush = true,
         ImageName = "hi",
         Build = new DockerBuildArgs {
            BuilderVersion = BuilderVersion.BuilderBuildKit,
            Context = "./",
            Dockerfile = "Dockerfile",
            Args = {
               // Using a resource output here as the arg value triggers a panic.  
               // Using a string literal or an output created from a Task<string> does not trigger.
               {"ARG_FROM_RESOURCE_OUTPUT", plugin.Id},
            },
         }
      });
   }
}

```

### Output of `pulumi about`

```
CLI          
Version      3.59.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME    VERSION
docker  4.1.0
dotnet  unknown

Host     
OS       debian
Version  11.6
Arch     x86_64

This project is written in dotnet: executable='/usr/bin/dotnet' version='7.0.201'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jlewicki-nevo
User           jlewicki-nevo
Organizations  jlewicki-nevo

Dependencies:
NAME           VERSION
Pulumi         3.54.1
Pulumi.Docker  4.1.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @jlewicki-nevo, thanks for opening an issue! I appreciate giving us the repro and confirming that the issue is only present in the 4.* major version.

**Comment by guineveresaenger** [comment]
Hi @jlewicki-nevo - I have a preliminary update for you with a workaround while we look into a permanent fix.
I can duplicate this behavior for some outputs from other resources, but not all. This tells me there's a missing step in the input parsing.

In the meantime - if you use [pulumi Apply](https://www.pulumi.com/docs/intro/concepts/inputs-outputs/#apply) on the other resource's Output, you should be able to get unblocked for now:

`let arg = otherResource.Field.apply(value => value)`
