### ISSUE TITLE
SIGSEGV when changing the image and server for image

### ISSUE THREAD

**Issue by emil-e** [pulumi/pulumi-docker#780]
### What happened?

I have an image where the image name is dependent on the `loginServer` of an Azure `containerregistry.Registry`. If I change the `registryName` of the registry I get a segfault in the docker provider:
```
➜  pulumi-bug pulumi up
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):  
Enter your passphrase to unlock config/secrets
Previewing update (test):
     Type                                        Name             Plan     Info
     pulumi:pulumi:Stack                         pulumi-bug-test           23 messages
     └─ azure-native:containerregistry:Registry  test-registry             1 error


Diagnostics:
  azure-native:containerregistry:Registry (test-registry):
    error: error reading from server: EOF

  pulumi:pulumi:Stack (pulumi-bug-test):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x101af2300]
    goroutine 14 [running]:
    github.com/pulumi/pulumi-docker/provider/v4.diffUpdates(...)
        /home/runner/work/pulumi-docker/pulumi-docker/provider/provider.go:297
    github.com/pulumi/pulumi-docker/provider/v4.(*dockerNativeProvider).Diff(0x140002f4000?, {0x30?, 0x30?}, 0x14000232230)
        /home/runner/work/pulumi-docker/pulumi-docker/provider/provider.go:267 +0x4a0
    github.com/pulumi/pulumi-docker/provider/v4.dockerHybridProvider.Diff({{}, {0x102abdba0, 0x27814, 0x27814}, {0x101d48e2c, 0x6}, {0x1020cc8b0, 0x140000cb180}, {0x1020cc800, 0x14000055180}}, ...)
        /home/runner/work/pulumi-docker/pulumi-docker/provider/hybrid.go:120 +0xcc
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler.func1({0x1020c0808, 0x14000135d40}, {0x101ff25e0?, 0x14000232230})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.71.0/proto/go/provider_grpc.pb.go:555 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x1020c0808, 0x14000135350}, {0x101ff25e0, 0x14000232230}, 0x140002fc1c0, 0x140005945d0)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f4
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler({0x102050c60?, 0x1400085aeb0}, {0x1020c0808, 0x14000135350}, 0x140002321c0, 0x140006b2020)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.71.0/proto/go/provider_grpc.pb.go:557 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x14000804000, {0x1020c8940, 0x140001bcea0}, 0x14000155680, 0x14000207a70, 0x102b01088, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1337 +0xc28
    google.golang.org/grpc.(*Server).handleStream(0x14000804000, {0x1020c8940, 0x140001bcea0}, 0x14000155680, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1714 +0x80c
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:959 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:957 +0x164
```

### Example

```TypeScript
import * as pulumi from "@pulumi/pulumi";
import * as resources from "@pulumi/azure-native/resources";
import * as storage from "@pulumi/azure-native/storage";
import * as containerregistry from "@pulumi/azure-native/containerregistry";
import * as docker from "@pulumi/docker";

const stack = pulumi.getStack();

const resourceGroup = new resources.ResourceGroup(`${stack}-resourcegroup`);

const registry = new containerregistry.Registry(`${stack}-registry`, {
  resourceGroupName: resourceGroup.name,
  registryName: `imagesforpulumibug${stack}`,
  sku: {
    name: containerregistry.SkuName.Basic,
  },
  adminUserEnabled: true,
});

const registryCredentials = containerregistry.listRegistryCredentialsOutput({
  resourceGroupName: resourceGroup.name,
  registryName: registry.name,
});

const image = new docker.Image(`${stack}-image`, {
  imageName: pulumi.interpolate`${registry.loginServer}/${stack}-myimage:latest`,
  registry: {
    server: registry.loginServer,
    username: registryCredentials.username?.apply((u) => u!),
    password: registryCredentials.passwords?.apply((ps) => ps![0].value!),
  },
  build: {
    dockerfile: "Dockerfile",
    context: ".",
    platform: "linux/amd64",
  },
});

export const repoDigest = image.repoDigest;
```

Deploy once and then try to deploy again but where the `registryName` is something else.

Sample Dockerfile
```Dockerfile
# syntax=docker/dockerfile:1
FROM scratch
COPY index.ts /
CMD ["echo", "hello"]
```

### Output of `pulumi about`

```
CLI          
Version      3.84.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.10.0
docker        4.4.1
nodejs        unknown

Host     
OS       darwin
Version  12.1
Arch     arm64

This project is written in nodejs: executable='/Users/emilsahlen/.nvm/versions/node/v14.17.6/bin/node' version='v14.17.6'

Current Stack: organization/pulumi-bug/test

TYPE                                     URN
pulumi:pulumi:Stack                      urn:pulumi:test::pulumi-bug::pulumi:pulumi:Stack::pulumi-bug-test
pulumi:providers:azure-native            urn:pulumi:test::pulumi-bug::pulumi:providers:azure-native::default_2_10_0
azure-native:resources:ResourceGroup     urn:pulumi:test::pulumi-bug::azure-native:resources:ResourceGroup::test-resourcegroup
azure-native:containerregistry:Registry  urn:pulumi:test::pulumi-bug::azure-native:containerregistry:Registry::test-registry
pulumi:providers:docker                  urn:pulumi:test::pulumi-bug::pulumi:providers:docker::default_4_4_1
docker:index/image:Image                 urn:pulumi:test::pulumi-bug::docker:index/image:Image::test-image


Found no pending operations associated with test

Backend        
Name           Emils-MBP.lan
URL            azblob://state?storage_account=dibricpulumi
User           emilsahlen
Organizations  

Dependencies:
NAME                  VERSION
@pulumi/azure-native  2.10.0
@pulumi/docker        4.4.1
@pulumi/pulumi        3.86.0
@types/node           16.18.57

Pulumi locates its logs in /var/folders/gh/xrzw20rj3pj5k9hv18x2pzbw0000gn/T/ by default
```

### Additional context

This is quite a blocker.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by emil-e** [comment]
I believe this is the same issue as https://github.com/pulumi/pulumi-docker/issues/766 but now with a repro as well.
